spring:
  application:
    name: ipp-dice-backend

# MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/ipp_dice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: YUyue0702
    driver-class-name: com.mysql.cj.jdbc.Driver
#  data:
#    # Redis Configuration
#    redis:
#          host: localhost
#          port: 6379
#          password:
#          lettuce:
#            pool:
#              max-active: 8
#              max-idle: 8
#              min-idle: 0

# MyBatis-Plus Configuration
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0